# experiment params
"NUM_SEEDS": 10 # number of vmapped seeds
"SEED": 3 # RNG'd between 0-100 via random.org

"HYP_TUNE": False # perform hyp tune

# wandb params
"ENTITY": "star-lab-gt"
"PROJECT": "DL Project"
"WANDB_MODE": "online"
"WANDB_LOG_ALL_SEEDS": True # will log separately the vmapped seeds

# where to save the params (if None, will not save)
"SAVE_PATH": "models"
"LOAD_PATH": "models/final-one-agent-one-landmark" # if None, will not load
# "LOAD_PATH": null

